=== PaulRaUnite/web-technologies/lab8/definition.dtd
<!ELEMENT document (page)*>
<!ELEMENT page (number, content)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT content (p | img)*>
<!ELEMENT p (#PCDATA)>
<!ELEMENT img (source, caption)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT caption (#PCDATA)>

=== PaulRaUnite/web-technologies/lab8/document.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="rules.xsl"?>
<!DOCTYPE document SYSTEM "definition.dtd">
<document xmlns="https://www.w3schools.com"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="document.xsd">
    <page>
        <number>8</number>
        <content>
            <img>
                <source>pic.png</source>
                <caption>Рисунок 1.1. Объединение сетей в Интернет</caption>
            </img>
            <p>Веб-страница – гипертекстовой ресурс Всемирной паутины, обычно напи-
                санный на языке HTML. Веб-страница может содержать ссылки для перехода
                на другие страницы, а также изображения, медиафайлы, например звуковые
                файлы и видео, Flash-анимацию и т.п.
            </p>
            <p>
                Программа, демонстрирующая веб-страницу, называется веб-браузер. Не-
                сколько веб-страниц, объединенных общей темой и дизайном, образуют веб-
                сайт.
            </p>
            <p>
                Веб-сервер (HTTP-сервер) – это программное обеспечение (ПО), предостав-
                ляющее доступ к сайтам. Наиболее популярными веб-серверами являются
                Apache (для ОС Windows и Unix) и Microsoft IIS (для Windows). Также веб-
                сервером называют компьютер, на котором установлено такое ПО.
            </p>
            <p>
                URL (Uniform Resource Locator) – адрес ресурса.
            </p>
            <p>
                Структура URL:
                протокол :// пользователь : пароль @ хост : порт / путь ? запрос
            </p>
        </content>
    </page>
    <page>
        <number>9</number>
        <content>
            <p>
                Некоторые элементы URL могут быть опущены. Чаще всего адрес имеет вид
                протокол :// хост / путь,
                где
                протокол – http, https, ftp, skype и др.
                хост – доменное имя (или IP-адрес)
                путь – местонахождение ресурса на хосте
            </p>
            <p>
                Например: http://www.redut.ru/forum/index.php
            </p>
            <p>
                При помощи URL можно ссылаться на любой открытый ресурс, будь то
                страница, изображение, файл для загрузки и т.д.
            </p>
            <p>
                Для обращения к сайту используют доменное имя. Доменное имя состоит из
                нескольких доменов, разделенных точкой.
            </p>
            <p>
                Например:
                maps.google.com – означает, что домен третьего уровня maps входит в домен
                второго уровня google, который в свою очередь входит в домен первого
                (верхнего) уровня com.
            </p>
            <p>
                Домены верхнего уровня делятся на общие и географические. Общие домены
                предназначены для определенного класса организаций, например:
                .com – для коммерческих сайтов;
                .org – для некоммерческих организаций;
                .net – для сайтов, чья деятельность связана с Интернетом.
            </p>
            <p>
                Географические домены выделяются для конкретной страны, например:
                .ru – Россия;
                .us – США
                .eu – Европейский союз
                .de – Германия
            </p>
            <p>
                Использование географического домена не всегда означает то, что сайт раз-
                мещается в соответствующей стране или имеет к ней какое-либо отношение.
                Например, многие телекомпании используют домен .tv островного государ-
                ства Тувалу.
            </p>
            <p>
                Помимо доменного имени для работы сайта необходим круглосуточно рабо-
                тающий веб-сервер, способный выдержать большие нагрузки. Услуга разме-
                щения веб-сайта на веб-сервере называется хостингом. Хостинг может быть
                платным или бесплатным. На платном хостинге, как правило, предоставляет-
                ся доменное имя второго уровня. За пользование хостингом и доменом взи-
            </p>
        </content>
    </page>
</document>
